import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'

import './globals.css'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ABC Academy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode,
  params: { locale: any }
}) {

  return (
    <html lang={locale}>
      <body className={outfit.className}>{children}</body>
    </html>
  )
}
